# Site settings
title: "ALICE O² Developer's Entry Point"
email: alice-o2-support@cern.ch
description: > # this means to ignore newlines until "baseurl:"
  Lean and clean web pages for our GitHub organization,
  to avoid having it returning 404. Most of the
  information should still come from https://alice-o2.web.cern.ch
baseurl: ""
url: "https://aliceo2group.github.io" # the base hostname & protocol for your site
categories: [main, infrastructure]

# Build settings
markdown: kramdown
highlighter: rouge

menu_header: ALICE O²
menu:
  - name: quickstart
    label: Quickstart
    items:
      - name: wp
        label: Work Packages
      - name: organisation
        label: Code organisation
      - name: fair-dpl
        label: FairMQ and DPL
      - name: build
        label: Build and install
      - name: devel
        label: Development process
      - name: help
        label: Getting help
  - name: advanced
    label: Advanced
    items:
      - name: binaries
        label: CVMFS and RPMs
      - name: cmake
        label: CMake
      - name: doxygen
        label: Doxygen
      - name: guideline
        label: Coding Guidelines
